FROM ubuntu:24.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ca-certificates cmake curl docker.io g++-13 gcc-13 git jq libicu74 libssl3t64 \
        ninja-build python3 python3-venv sudo tar unzip zip \
    && rm -rf /var/lib/apt/lists/*

ENV RUNNER_ALLOW_RUNASROOT=1

ENTRYPOINT []
